-- TopRentals — Supabase/PostgreSQL schema
-- Source of truth: docs/analysis/data_model.md (SharePoint -> PostgreSQL mapping).
-- Generated by hand from that doc. Where the doc marks something "recommended",
-- the recommendation was taken (e.g. estado_activo/estado_alta/estado_usuario -> boolean
-- flags instead of enums, since they are all binary soft-delete/active flags).
--
-- NOTE: the doc's "## Tables" section defines 21 tables (edificios..documentos), not 24.
-- This file implements exactly those 21, in FK-dependency order.
--
-- Apply order: schema.sql -> seed.sql -> storage-buckets.sql (see README.md).

-- ============================================================================
-- ENUMS
-- ============================================================================
-- Only genuine multi-value workflow/category enums get a PG type. Binary
-- Activo/Inactivo, Alta/Baja and SI/NO flags become boolean columns instead
-- (see data_model.md "estado_activo ... recommended: boolean").

CREATE TYPE estado_ot AS ENUM (
  'Pendiente', 'Asignada', 'Cerrada', 'Cerrada F', 'Cerrada V', 'Anulada'
);

CREATE TYPE tipo_ot AS ENUM (
  'ORDEN DE TRABAJO', 'SOLICITUD OT'
);

CREATE TYPE prioridad AS ENUM (
  'Alta', 'Media', 'Baja'
);

CREATE TYPE perfil_usuario AS ENUM (
  'Admin', 'Tecnico', 'Gerencia', 'Compras', 'Supervisor Ventilaciones', 'Recepcion', 'Operador'
);

CREATE TYPE estado_compra AS ENUM (
  'Pendiente', 'Aprobacion', 'Aprobada', 'Rechazada', 'Recibida', 'En proceso'
);

CREATE TYPE estado_aprobacion AS ENUM (
  'Pendiente', 'Aprobada Supervision', 'Aprobada', 'Rechazada', 'Recibida', 'En Aprobacion'
);

CREATE TYPE estado_ventilacion AS ENUM (
  'Pendiente', 'Programada', 'Asignada', 'Realizada', 'Eliminada'
);

CREATE TYPE tipo_salida_stock AS ENUM (
  'ASIGNACION', 'CONSUMIBLE', 'DEVOLUCION', 'TRASLADO', 'DEVUELTO'
);

-- Used by perfiles_permisos.aplicacion. iconos_app.app stays plain text
-- because it also carries the value 'Mobile', which is outside this set.
CREATE TYPE aplicacion_app AS ENUM (
  'Desktop', 'Mantenimiento'
);

-- ============================================================================
-- 1. edificios
-- ============================================================================
CREATE TABLE edificios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  pais text,
  -- zona/grupo_stock: the hardcoded building clusters from the Power Apps
  -- screens (geographic zone, shared-stock pair) become real columns.
  zona text NULL,
  grupo_stock text NULL,
  activo boolean NOT NULL DEFAULT true, -- was Status_E 'Activo'/'Inactivo'
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NULL
);

-- ============================================================================
-- 2. articulos
-- ============================================================================
CREATE TABLE articulos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo text,
  nombre text NOT NULL,
  precio_unitario numeric(12, 2),
  corte text, -- meaning unclear per data_model.md open questions (likely stock_minimo)
  activo boolean NOT NULL DEFAULT true, -- was Status_AR 'Activo'/'Inactivo'
  detalle text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NULL
);

-- ============================================================================
-- 3. frecuencias
-- ============================================================================
CREATE TABLE frecuencias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text,
  dias numeric NOT NULL,
  activo boolean NOT NULL DEFAULT true, -- was Status_FE 'Activo'/'Inactivo'
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 4. unidades
-- ============================================================================
CREATE TABLE unidades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_client text,
  depto text,
  torre text,
  edificio_id bigint NULL REFERENCES edificios (id) ON DELETE RESTRICT,
  tipo_depto text,
  tipo_sector text,
  activa boolean NOT NULL DEFAULT true, -- was Status_ABMUnid 'Alta' (folded per open question)
  frecuencia_ventilacion_dias numeric,
  requiere_ventilacion boolean, -- was Ventilacion_ABMUnid 'SI'/'NO'
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NULL
);

-- ============================================================================
-- 5. usuarios
-- ============================================================================
CREATE TABLE usuarios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id uuid NULL UNIQUE, -- FK to auth.users added below via guarded DO block
  nombre text,
  apellido text,
  concat_name text, -- text-join key used by Tecnico_IN/Asignador_OT/Usuario_* everywhere: KEEP
  usuario_app text NOT NULL UNIQUE,
  dni numeric,
  fecha_nac date,
  mail text,
  num_cel text,
  edificio_id bigint NULL REFERENCES edificios (id) ON DELETE SET NULL,
  edificio_default text,
  pais text,
  perfil perfil_usuario NOT NULL,
  validado boolean,
  wapp_default text,
  mnt_global text,
  aplicacion text,
  es_testing boolean,
  activo boolean NOT NULL DEFAULT true, -- was Status_Usr 'ALTA'/'BAJA'
  legacy_id_usr numeric,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NULL
);

-- Guarded: only wire the auth.users FK when the auth schema actually exists,
-- so this script also runs unchanged on plain Postgres (e.g. local dev/tests).
DO $$
BEGIN
  IF to_regclass('auth.users') IS NOT NULL THEN
    ALTER TABLE usuarios
      ADD CONSTRAINT usuarios_auth_user_id_fkey
      FOREIGN KEY (auth_user_id) REFERENCES auth.users (id) ON DELETE SET NULL;
  END IF;
END;
$$;

-- ============================================================================
-- 6. perfiles_permisos
-- ============================================================================
CREATE TABLE perfiles_permisos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modulo text NOT NULL,
  admin text,
  operador text,
  tecnico text,
  recepcion text,
  compras text,
  jefe_operativo text,
  orden numeric,
  imagen_path text,
  imagen_no_selected_path text,
  aplicacion aplicacion_app NOT NULL,
  activo boolean NOT NULL DEFAULT true, -- was Status_LPP 'Activo'/'Inactivo'
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 7. iconos_app
-- ============================================================================
CREATE TABLE iconos_app (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icono_path text,
  app text, -- 'Desktop'/'Mobile' — plain text, NOT aplicacion_app (values don't match 1:1)
  descripcion text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (app, descripcion) -- App.OnStart lookup key
);

-- ============================================================================
-- 8. emails_notificacion
-- ============================================================================
CREATE TABLE emails_notificacion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modulo text NOT NULL,
  emails text,
  edificio text,
  a_tecnolav text,
  activo boolean NOT NULL DEFAULT true, -- was Status_E 'Activo'/'Inactivo'
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 9. ordenes_trabajo
-- ============================================================================
CREATE TABLE ordenes_trabajo (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_univoco text NOT NULL UNIQUE,
  status estado_ot NOT NULL,
  tipo tipo_ot,
  prioridad prioridad,
  tipo_trabajo text,
  tipo_tarea text,
  tipo_prioridad text,
  unidad_id bigint NULL REFERENCES unidades (id) ON DELETE RESTRICT,
  torre text,
  departamento text,
  concat_activo text,
  tecnico_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  asignador_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  user_carga_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  fecha_inicio date,
  fecha_cierre date,
  fecha_asignada date,
  dias_estimado numeric,
  personas_requeridas numeric,
  detalle text,
  observaciones text,
  obs_resuelto text,
  obs_asignacion text,
  obs_cierre text,
  -- Self-FK: a replicated OT stores the source OT's id. Deferred so the
  -- migration can insert all OT rows first, then UPDATE this column, all
  -- inside one transaction, without violating the constraint mid-batch.
  orden_revision_id bigint NULL REFERENCES ordenes_trabajo (id) ON DELETE SET NULL
    DEFERRABLE INITIALLY DEFERRED,
  problema text,
  desde text,
  version_app text,
  hora time,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 10. bitacoras
-- ============================================================================
CREATE TABLE bitacoras (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_trabajo_id bigint NOT NULL REFERENCES ordenes_trabajo (id) ON DELETE CASCADE,
  id_univoco_bitacora text UNIQUE, -- fotos_bitacora joins on this
  descripcion text,
  fecha timestamptz,
  usuario_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  version_app text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 11. fotos_bitacora
-- ============================================================================
CREATE TABLE fotos_bitacora (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_trabajo_id bigint NULL REFERENCES ordenes_trabajo (id) ON DELETE CASCADE,
  bitacora_id bigint NULL REFERENCES bitacoras (id) ON DELETE CASCADE,
  foto_path text, -- Storage bucket 'bitacoras' object key (was base64 Foto_FB)
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 12. repuestos_ot
-- ============================================================================
CREATE TABLE repuestos_ot (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orden_trabajo_id bigint NOT NULL REFERENCES ordenes_trabajo (id) ON DELETE CASCADE,
  articulo_id bigint NULL REFERENCES articulos (id) ON DELETE RESTRICT,
  repuesto text,
  cantidad numeric,
  edificio text,
  usuario_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  fecha timestamptz,
  activo boolean NOT NULL DEFAULT true, -- was Status_ROT 'Activo'/'Inactivo'
  version_app text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 13. stock
-- ============================================================================
CREATE TABLE stock (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_univoco text,
  articulo_id bigint NOT NULL REFERENCES articulos (id) ON DELETE RESTRICT,
  cantidad numeric NOT NULL DEFAULT 0,
  precio_unitario numeric(12, 2),
  condicion_corte numeric,
  activo boolean NOT NULL DEFAULT true, -- was Status_ST 'Activo'/'Inactivo'
  usuario_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  fecha timestamptz,
  ultima_mod text,
  desde text,
  version_app text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 14. stock_edificios (junction: stock <-> edificios, M:N)
-- ============================================================================
CREATE TABLE stock_edificios (
  stock_id bigint NOT NULL REFERENCES stock (id) ON DELETE CASCADE,
  edificio_id bigint NOT NULL REFERENCES edificios (id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (stock_id, edificio_id)
);

-- ============================================================================
-- 15. movimientos_stock (append-only audit trail: FKs SET NULL, never CASCADE)
-- ============================================================================
CREATE TABLE movimientos_stock (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  articulo_id bigint NULL REFERENCES articulos (id) ON DELETE SET NULL,
  articulo_raw text, -- original IDArticulo_MS value, audit (column is dirty: id or codigo)
  concat_articulo text,
  articulo text,
  cant_anterior numeric,
  cant_posterior numeric,
  costo_anterior numeric,
  costo_posterior numeric,
  stock_min_anterior numeric,
  stock_min_posterior numeric,
  edificio_id bigint NULL REFERENCES edificios (id) ON DELETE SET NULL,
  edificio_raw text, -- original IDEdificio_MS value (may be multi-valued '16;17')
  edificio text,
  edificio_traslado text,
  desde text,
  tipo_movimiento text,
  cantidad numeric,
  usuario_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  fecha timestamptz,
  version_app text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 16. salidas_stock
-- ============================================================================
CREATE TABLE salidas_stock (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  articulo_id bigint NULL REFERENCES articulos (id) ON DELETE RESTRICT,
  -- Stock row actually debited: the only safe credit target for edit/devolución.
  -- NULL on rows migrated from SharePoint (the source has no such column).
  stock_id bigint NULL REFERENCES stock (id) ON DELETE SET NULL,
  concat_articulo text,
  tecnico_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  tipo tipo_salida_stock,
  fecha_salida date,
  fecha_reingreso date,
  uso text,
  centro_de_costo text,
  cantidad numeric,
  usuario_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  fecha timestamptz,
  version_app text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 17. compras
-- ============================================================================
CREATE TABLE compras (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_compra text UNIQUE, -- detalle_compras + aprobaciones join on this
  usuario_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  usuario_compra text,
  urgencia text,
  observacion text,
  obs_recibir text,
  fecha date,
  cantidad_total numeric,
  monto_total numeric(14, 2),
  status estado_compra NOT NULL,
  cargo text, -- legacy, read once in UI
  sector_pedido text, -- legacy, never written by screens
  version_app text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 18. detalle_compras
-- ============================================================================
CREATE TABLE detalle_compras (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id bigint NOT NULL REFERENCES compras (id) ON DELETE CASCADE,
  id_univoco text,
  articulo_id bigint NULL REFERENCES articulos (id) ON DELETE RESTRICT,
  articulo text,
  edificio_id bigint NULL REFERENCES edificios (id) ON DELETE RESTRICT,
  edificio text,
  cantidad numeric,
  recibido numeric,
  costo_unitario numeric(12, 2),
  cant_min numeric,
  costo_total numeric(14, 2),
  activo boolean NOT NULL DEFAULT true, -- was Status_DC 'Activo'/'Inactivo' (line soft-delete)
  usuario_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  fecha timestamptz,
  version_app text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 19. aprobaciones
-- ============================================================================
CREATE TABLE aprobaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id bigint NOT NULL REFERENCES compras (id) ON DELETE CASCADE,
  status estado_aprobacion NOT NULL,
  fecha date,
  urgencia text,
  tecnico text,
  obs_compra text,
  fecha_aprobada date,
  obs_rechazo text,
  user_gen_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  user_aprob_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  cantidad numeric,
  monto numeric(14, 2),
  sector text,
  version_app text,
  hora time,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 20. ventilaciones
-- ============================================================================
CREATE TABLE ventilaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado estado_ventilacion NOT NULL,
  unidad_id bigint NULL REFERENCES unidades (id) ON DELETE RESTRICT,
  direccion_edificio text,
  edificio text,
  habitacion text,
  frecuencia_dias numeric, -- VALUE copy from unidades.frecuencia_ventilacion_dias, NOT an FK
  fecha_ultima date,
  proxima_limpieza date,
  fecha_programada date,
  obs_adelanto text,
  obs_resuelto text,
  asignado_id bigint NULL REFERENCES usuarios (id) ON DELETE SET NULL,
  fecha_asignado timestamptz,
  version_asignado text,
  fecha_finalizacion timestamptz,
  version_resuelto text,
  es_incidente boolean, -- was EsIncidente_VE 'SI'/'NO'
  orden numeric,
  -- Deviation from data_model.md: the doc doesn't give ventilaciones a photo
  -- column, but finalizar_ventilacion() (below) takes p_foto_path and needs
  -- somewhere to put the closing photo's Storage object key.
  foto_path text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 21. documentos (metadata only; binaries live in Storage)
-- ============================================================================
CREATE TABLE documentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text,
  storage_path text NOT NULL,
  carpeta text, -- 'Ordenes'|'Compras'|'Bitacoras'
  orden_trabajo_id bigint NULL REFERENCES ordenes_trabajo (id) ON DELETE CASCADE,
  compra_id bigint NULL REFERENCES compras (id) ON DELETE CASCADE,
  content_type text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- INDEXES — every FK column, plus the explicitly requested workflow indexes
-- ============================================================================
CREATE INDEX idx_unidades_edificio_id ON unidades (edificio_id);

CREATE INDEX idx_usuarios_edificio_id ON usuarios (edificio_id);

CREATE INDEX idx_ordenes_trabajo_unidad_id ON ordenes_trabajo (unidad_id);
CREATE INDEX idx_ordenes_trabajo_tecnico_id ON ordenes_trabajo (tecnico_id);
CREATE INDEX idx_ordenes_trabajo_asignador_id ON ordenes_trabajo (asignador_id);
CREATE INDEX idx_ordenes_trabajo_user_carga_id ON ordenes_trabajo (user_carga_id);
CREATE INDEX idx_ordenes_trabajo_orden_revision_id ON ordenes_trabajo (orden_revision_id);
CREATE INDEX idx_ordenes_trabajo_status ON ordenes_trabajo (status);

CREATE INDEX idx_bitacoras_orden_trabajo_id ON bitacoras (orden_trabajo_id);
CREATE INDEX idx_bitacoras_usuario_id ON bitacoras (usuario_id);

CREATE INDEX idx_fotos_bitacora_orden_trabajo_id ON fotos_bitacora (orden_trabajo_id);
CREATE INDEX idx_fotos_bitacora_bitacora_id ON fotos_bitacora (bitacora_id);

CREATE INDEX idx_repuestos_ot_orden_trabajo_id ON repuestos_ot (orden_trabajo_id);
CREATE INDEX idx_repuestos_ot_articulo_id ON repuestos_ot (articulo_id);
CREATE INDEX idx_repuestos_ot_usuario_id ON repuestos_ot (usuario_id);

CREATE INDEX idx_stock_articulo_id ON stock (articulo_id);
CREATE INDEX idx_stock_usuario_id ON stock (usuario_id);

CREATE INDEX idx_stock_edificios_edificio_id ON stock_edificios (edificio_id);

CREATE INDEX idx_movimientos_stock_articulo_id ON movimientos_stock (articulo_id);
CREATE INDEX idx_movimientos_stock_edificio_id ON movimientos_stock (edificio_id);
CREATE INDEX idx_movimientos_stock_usuario_id ON movimientos_stock (usuario_id);
CREATE INDEX idx_movimientos_stock_fecha ON movimientos_stock (fecha);

CREATE INDEX idx_salidas_stock_articulo_id ON salidas_stock (articulo_id);
CREATE INDEX idx_salidas_stock_tecnico_id ON salidas_stock (tecnico_id);
CREATE INDEX idx_salidas_stock_usuario_id ON salidas_stock (usuario_id);

CREATE INDEX idx_compras_usuario_id ON compras (usuario_id);
CREATE INDEX idx_compras_status ON compras (status);

CREATE INDEX idx_detalle_compras_compra_id ON detalle_compras (compra_id);
CREATE INDEX idx_detalle_compras_articulo_id ON detalle_compras (articulo_id);
CREATE INDEX idx_detalle_compras_edificio_id ON detalle_compras (edificio_id);
CREATE INDEX idx_detalle_compras_usuario_id ON detalle_compras (usuario_id);

CREATE INDEX idx_aprobaciones_compra_id ON aprobaciones (compra_id);
CREATE INDEX idx_aprobaciones_user_gen_id ON aprobaciones (user_gen_id);
CREATE INDEX idx_aprobaciones_user_aprob_id ON aprobaciones (user_aprob_id);

CREATE INDEX idx_ventilaciones_unidad_id ON ventilaciones (unidad_id);
CREATE INDEX idx_ventilaciones_asignado_id ON ventilaciones (asignado_id);
CREATE INDEX idx_ventilaciones_estado ON ventilaciones (estado);

CREATE INDEX idx_documentos_orden_trabajo_id ON documentos (orden_trabajo_id);
CREATE INDEX idx_documentos_compra_id ON documentos (compra_id);

-- ============================================================================
-- RPC: finalizar_ventilacion
-- Closes a ventilacion cycle and opens the next one atomically:
--   1) marks the given row 'Realizada' (obs + closing photo + timestamp)
--   2) inserts the next cycle row: 'Pendiente', proxima_limpieza = today + frecuencia_dias
-- Both steps run inside one function call, i.e. one transaction — if either
-- statement fails the whole thing rolls back, so there's never a ventilacion
-- left "Realizada" without its successor (or vice versa).
-- ============================================================================
CREATE OR REPLACE FUNCTION finalizar_ventilacion(
  p_id bigint,
  p_obs text,
  p_foto_path text
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
  v_unidad_id bigint;
  v_direccion_edificio text;
  v_edificio text;
  v_habitacion text;
  v_frecuencia_dias numeric;
  v_asignado_id bigint;
  v_new_id bigint;
BEGIN
  UPDATE ventilaciones
  SET
    estado = 'Realizada',
    obs_resuelto = p_obs,
    foto_path = coalesce(p_foto_path, foto_path),
    fecha_finalizacion = now()
  WHERE id = p_id
  RETURNING
    unidad_id, direccion_edificio, edificio, habitacion, frecuencia_dias, asignado_id
    INTO v_unidad_id, v_direccion_edificio, v_edificio, v_habitacion, v_frecuencia_dias, v_asignado_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'finalizar_ventilacion: ventilacion % not found', p_id;
  END IF;

  INSERT INTO ventilaciones (
    estado, unidad_id, direccion_edificio, edificio, habitacion,
    frecuencia_dias, fecha_ultima, proxima_limpieza, asignado_id
  )
  VALUES (
    'Pendiente', v_unidad_id, v_direccion_edificio, v_edificio, v_habitacion,
    v_frecuencia_dias, current_date, current_date + coalesce(v_frecuencia_dias, 0)::int, v_asignado_id
  )
  RETURNING id INTO v_new_id;

  RETURN v_new_id;
END;
$$;

COMMENT ON FUNCTION finalizar_ventilacion(bigint, text, text) IS
  'Closes a ventilacion cycle (estado=Realizada, obs + foto) and atomically '
  'inserts the next cycle (estado=Pendiente, proxima_limpieza = current_date + '
  'frecuencia_dias). Returns the new row''s id. Replaces the desktop/mobile '
  '"finalizar ventilacion" flow.';

-- ============================================================================
-- ROW LEVEL SECURITY — placeholder policies only
-- TODO: replace with real per-perfil policies once the backend/auth model is
-- decided (see data_model.md "## Auth"). For now every table is RLS-enabled
-- with a single permissive policy so `anon`/service-role access stops working
-- accidentally, while any authenticated Supabase user can read/write everything.
-- ============================================================================
DO $$
DECLARE
  t text;
BEGIN
  FOR t IN SELECT unnest(ARRAY[
    'edificios', 'articulos', 'frecuencias', 'unidades', 'usuarios',
    'perfiles_permisos', 'iconos_app', 'emails_notificacion', 'ordenes_trabajo',
    'bitacoras', 'fotos_bitacora', 'repuestos_ot', 'stock', 'stock_edificios',
    'movimientos_stock', 'salidas_stock', 'compras', 'detalle_compras',
    'aprobaciones', 'ventilaciones', 'documentos'
  ])
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format(
      'CREATE POLICY %I ON %I FOR ALL TO authenticated USING (true) WITH CHECK (true);',
      t || '_todo_authenticated_all', t
    );
  END LOOP;
END;
$$;
