// Bundles the Vercel Cron handler into a single self-contained ESM file at
// api/catalog-sync.js. @vercel/node transpiles api/*.ts per-file (no bundling)
// and leaves ".ts" import specifiers verbatim — which Node's ESM loader can't
// resolve at runtime (ERR_MODULE_NOT_FOUND). Pre-bundling here sidesteps that:
// the deployed function has zero relative imports, only external npm deps.
//
// Runs as part of `npm run build` (so Vercel regenerates it on every deploy —
// no drift) and standalone via `npm run build:api`.
import { build } from 'esbuild';

await build({
  entryPoints: ['scripts/sync/vercel-handler.ts'],
  outfile: 'api/catalog-sync.js',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node18',
  // Available in the function's node_modules at runtime; @vercel/node is type-only here.
  external: ['@supabase/supabase-js', '@vercel/node'],
  banner: {
    js: '// GENERATED by scripts/build-api.mjs — do not edit. Source: scripts/sync/vercel-handler.ts',
  },
});
