// GENERATED by scripts/build-api.mjs — do not edit. Source: scripts/sync/vercel-handler.ts

// scripts/sync/vercel-handler.ts
import { createClient as createClient2 } from "@supabase/supabase-js";

// scripts/migrate/src/graph.ts
var GRAPH_ROOT = "https://graph.microsoft.com/v1.0";
async function graphFetchJson(url, token, init) {
  const res = await fetch(url, {
    ...init,
    headers: { Authorization: `Bearer ${token}`, ...init?.headers ?? {} }
  });
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`Graph request failed (${res.status} ${res.statusText}) for ${url}: ${body.slice(0, 500)}`);
  }
  return res.json();
}
function createGraphClient(env) {
  let cachedToken = null;
  async function getAccessToken() {
    if (cachedToken && cachedToken.expiresAt - Date.now() > 6e4) {
      return cachedToken.value;
    }
    const url = `https://login.microsoftonline.com/${env.tenantId}/oauth2/v2.0/token`;
    const body = new URLSearchParams({
      client_id: env.clientId,
      client_secret: env.clientSecret,
      scope: "https://graph.microsoft.com/.default",
      grant_type: "client_credentials"
    });
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body
    });
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      throw new Error(`Azure AD token request failed (${res.status}): ${text.slice(0, 500)}`);
    }
    const json = await res.json();
    cachedToken = { value: json.access_token, expiresAt: Date.now() + json.expires_in * 1e3 };
    return cachedToken.value;
  }
  async function resolveSiteId(spSiteUrl) {
    const url = new URL(spSiteUrl);
    const token = await getAccessToken();
    const path = encodeURI(`${GRAPH_ROOT}/sites/${url.hostname}:${url.pathname}`);
    const site = await graphFetchJson(path, token);
    return site.id;
  }
  async function resolveListId(siteId, displayName) {
    const token = await getAccessToken();
    const filter = encodeURIComponent(`displayName eq '${displayName.replace(/'/g, "''")}'`);
    const url = `${GRAPH_ROOT}/sites/${siteId}/lists?$filter=${filter}`;
    const page = await graphFetchJson(url, token);
    const match = page.value[0];
    if (!match) throw new Error(`SharePoint list not found by displayName: "${displayName}"`);
    return match.id;
  }
  async function fetchAllItems(siteId, listId) {
    const token = await getAccessToken();
    const items = [];
    let url = `${GRAPH_ROOT}/sites/${siteId}/lists/${listId}/items?$expand=fields&$top=999`;
    while (url) {
      const page = await graphFetchJson(url, token);
      for (const raw of page.value) items.push({ id: raw.id, fields: raw.fields ?? {} });
      url = page["@odata.nextLink"] ?? null;
    }
    return items;
  }
  async function listDrives(siteId) {
    const token = await getAccessToken();
    const page = await graphFetchJson(`${GRAPH_ROOT}/sites/${siteId}/drives`, token);
    return page.value;
  }
  async function listDriveItemsRecursive(driveId) {
    const token = await getAccessToken();
    const out = [];
    async function walk(itemId, parentPath) {
      let url = `${GRAPH_ROOT}/drives/${driveId}/items/${itemId}/children?$expand=listItem($expand=fields)&$top=200`;
      while (url) {
        const page = await graphFetchJson(url, token);
        for (const child of page.value) {
          const isFolder = Boolean(child.folder);
          if (isFolder) {
            await walk(child.id, parentPath ? `${parentPath}/${child.name}` : child.name);
          } else {
            out.push({
              id: child.id,
              name: child.name,
              isFolder: false,
              parentPath,
              size: child.size ?? 0,
              mimeType: child.file?.mimeType ?? null,
              createdDateTime: child.createdDateTime ?? null,
              listItemFields: child.listItem?.fields ?? null
            });
          }
        }
        url = page["@odata.nextLink"] ?? null;
      }
    }
    await walk("root", "");
    return out;
  }
  async function downloadDriveItemContent(driveId, itemId) {
    const token = await getAccessToken();
    const res = await fetch(`${GRAPH_ROOT}/drives/${driveId}/items/${itemId}/content`, {
      headers: { Authorization: `Bearer ${token}` }
    });
    if (!res.ok) throw new Error(`Failed to download drive item ${itemId} (${res.status})`);
    return Buffer.from(await res.arrayBuffer());
  }
  return {
    getAccessToken,
    resolveSiteId,
    resolveListId,
    fetchAllItems,
    listDrives,
    listDriveItemsRecursive,
    downloadDriveItemContent
  };
}

// scripts/sync/catalog-sync.ts
import { pathToFileURL } from "node:url";
import { createClient } from "@supabase/supabase-js";

// scripts/migrate/src/coerce.ts
function emptyToNull(value) {
  if (value == null) return null;
  const s = String(value).trim();
  if (s === "" || s.toLowerCase() === "null") return null;
  return s;
}
function parseDMY(value) {
  const s = emptyToNull(value);
  if (!s) return null;
  const match = /^(\d{2})\/(\d{2})\/(\d{4})$/.exec(s);
  if (!match) return null;
  const [, d, m, y] = match;
  const date = /* @__PURE__ */ new Date(`${y}-${m}-${d}T00:00:00Z`);
  const isReal = !Number.isNaN(date.getTime()) && date.getUTCFullYear() === Number(y) && date.getUTCMonth() + 1 === Number(m) && date.getUTCDate() === Number(d);
  return isReal ? `${y}-${m}-${d}` : null;
}
function parseHora(value) {
  const s = emptyToNull(value);
  if (!s) return null;
  const match = /^(\d{1,2}):(\d{2})$/.exec(s);
  if (!match) return null;
  const h = Number(match[1]);
  const min = Number(match[2]);
  if (h > 23 || min > 59) return null;
  return `${String(h).padStart(2, "0")}:${String(min).padStart(2, "0")}:00`;
}
function combineDateTime(dateValue, horaValue) {
  const date = parseDMY(dateValue);
  if (!date) return null;
  const hora = parseHora(horaValue) ?? "00:00:00";
  return `${date}T${hora}`;
}
function parseNumber(value) {
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  const s = emptyToNull(value);
  if (!s) return null;
  let cleaned = s.replace(/\s/g, "");
  const hasDot = cleaned.includes(".");
  const hasComma = cleaned.includes(",");
  if (hasDot && hasComma) {
    const decimalSep = cleaned.lastIndexOf(",") > cleaned.lastIndexOf(".") ? "," : ".";
    const thousandsSep = decimalSep === "," ? "." : ",";
    cleaned = cleaned.split(thousandsSep).join("");
    cleaned = cleaned.replace(decimalSep, ".");
  } else if (hasComma) {
    cleaned = cleaned.replace(",", ".");
  }
  const n = Number(cleaned);
  return Number.isFinite(n) ? n : null;
}
function siNoToBool(value) {
  const s = emptyToNull(value)?.toUpperCase() ?? null;
  if (s === null) return null;
  if (s === "SI" || s === "TRUE" || s === "1" || s === "YES") return true;
  if (s === "NO" || s === "FALSE" || s === "0") return false;
  return null;
}
function activoToBool(value) {
  const s = emptyToNull(value)?.toUpperCase() ?? null;
  if (s === null) return null;
  if (s === "ACTIVO") return true;
  if (s === "INACTIVO") return false;
  return null;
}
function altaBajaToBool(value) {
  const s = emptyToNull(value)?.toUpperCase() ?? null;
  if (s === null) return null;
  if (s === "ALTA") return true;
  if (s === "BAJA") return false;
  return null;
}

// scripts/migrate/src/mappings.ts
var SP_LISTS = {
  edificios: "99.ABM_Edificios",
  articulos: "99.ABM_Articulos",
  frecuencias: "99.ABM_Frecuencias",
  unidades: "99.ABM_TipoUnidades",
  usuarios: "00.Usuarios",
  perfilesPermisos: "99.ABM_ListaPermisosPerfilesV3",
  iconosApp: "99.ABM_IconosApp",
  emailsNotificacion: "99.ABM_Emails",
  ordenesTrabajo: "07.OrdenesTrabajo",
  bitacoras: "15.Bitacoras",
  fotosBitacora: "16.FotoBitacora",
  repuestosOt: "10.RepuestosOT",
  stock: "08.Stock",
  movimientosStock: "08.MovimientoStock",
  salidasStock: "09.SalidaStock",
  compras: "14.Compras",
  detalleCompras: "15.DetalleCompras",
  aprobaciones: "16.Aprobaciones",
  ventilaciones: "19.Ventilaciones"
};
function isDateTimeMapping(m) {
  return m.kind === "datetime";
}
function coerceColumn(type, value) {
  switch (type) {
    case "text":
    case "passthrough":
    case "iso":
      return emptyToNull(value);
    case "number":
      return parseNumber(value);
    case "money":
      return parseNumber(value);
    case "date":
      return parseDMY(value);
    case "time":
      return parseHora(value);
    case "bool_si_no":
      return siNoToBool(value);
    // Soft-delete flags: every activo/activa column is NOT NULL DEFAULT true in schema.sql,
    // so an empty/unknown SharePoint Status_* means "active" (matches the DB default) — never null.
    case "bool_activo_inactivo":
      return activoToBool(value) ?? true;
    case "bool_alta_baja":
      return altaBajaToBool(value) ?? true;
  }
}
function mapRow(mappings, fields) {
  const row = {};
  for (const m of mappings) {
    if (isDateTimeMapping(m)) {
      row[m.pg] = combineDateTime(fields[m.spDate], fields[m.spHora]);
    } else {
      row[m.pg] = coerceColumn(m.type, fields[m.sp]);
    }
  }
  return row;
}
var edificios = [
  { pg: "nombre", sp: "Edificio_E", type: "text" },
  { pg: "pais", sp: "Pais_E", type: "text" },
  { pg: "activo", sp: "Status_E", type: "bool_activo_inactivo" },
  { pg: "created_at", sp: "Created", type: "iso" },
  { pg: "updated_at", sp: "Modified", type: "iso" }
];
var articulos = [
  { pg: "codigo", sp: "Codigo_AR", type: "text" },
  { pg: "nombre", sp: "Articulo_AR", type: "text" },
  { pg: "precio_unitario", sp: "PrecioUnitario_AR", type: "money" },
  { pg: "corte", sp: "Corte_AR", type: "text" },
  { pg: "activo", sp: "Status_AR", type: "bool_activo_inactivo" },
  { pg: "detalle", sp: "Detalle_AR", type: "text" },
  { pg: "created_at", sp: "Created", type: "iso" },
  { pg: "updated_at", sp: "Modified", type: "iso" }
];
var frecuencias = [
  { pg: "nombre", sp: "Title", type: "text" },
  { pg: "dias", sp: "field_1", type: "number" },
  // Frecuencia_FE
  { pg: "activo", sp: "field_2", type: "bool_activo_inactivo" },
  // Status_FE
  { pg: "created_at", sp: "Created", type: "iso" }
];
var unidades = [
  { pg: "id_client", sp: "Title", type: "text" },
  { pg: "depto", sp: "field_1", type: "text" },
  // Depto_ABMUnid
  { pg: "torre", sp: "field_2", type: "text" },
  // Torre_ABMUnid
  { pg: "tipo_depto", sp: "field_3", type: "text" },
  // TipoDepto_ABMUnid
  { pg: "tipo_sector", sp: "TipoSector_ABMUnid", type: "text" },
  { pg: "activa", sp: "Status_ABMUnid", type: "bool_alta_baja" },
  // only 'Alta' seen in formulas
  { pg: "frecuencia_ventilacion_dias", sp: "Frecuencia_ABMUnid", type: "number" },
  { pg: "requiere_ventilacion", sp: "Ventilacion_ABMUnid", type: "bool_si_no" },
  { pg: "created_at", sp: "Created", type: "iso" },
  { pg: "updated_at", sp: "Modified", type: "iso" }
];
var unidadesResolutions = [
  // Torre_ABMUnid (field_2) name resolved against edificios.nombre.
  { pg: "edificio_id", sp: "field_2", via: "edificioNombre" }
];
var perfilesPermisos = [
  { pg: "modulo", sp: "field_1", type: "text" },
  // Modulo_LPP
  { pg: "admin", sp: "field_2", type: "text" },
  { pg: "operador", sp: "field_3", type: "text" },
  { pg: "recepcion", sp: "field_4", type: "text" },
  { pg: "tecnico", sp: "field_5", type: "text" },
  { pg: "compras", sp: "Compras_LPP", type: "text" },
  { pg: "jefe_operativo", sp: "JefeOperatico_LPP", type: "text" },
  { pg: "orden", sp: "field_8", type: "number" },
  // SortByColumns_LPP
  { pg: "imagen_path", sp: "field_9", type: "text" },
  // Imagen_LPP — base64 -> Storage 'branding' at load
  { pg: "imagen_no_selected_path", sp: "field_10", type: "text" },
  // ImagenNoSelected_LPP — same
  { pg: "aplicacion", sp: "field_11", type: "passthrough" },
  // Aplicacion_LPP
  { pg: "activo", sp: "field_12", type: "bool_activo_inactivo" },
  // Status_LPP
  { pg: "created_at", sp: "Created", type: "iso" }
];
var iconosApp = [
  { pg: "icono_path", sp: "Icono_IA", type: "text" },
  // base64 -> Storage 'branding' at load
  { pg: "app", sp: "App_IA", type: "text" },
  { pg: "descripcion", sp: "Descripcion_IA", type: "text" },
  { pg: "created_at", sp: "Created", type: "iso" }
];
var emailsNotificacion = [
  { pg: "modulo", sp: "Modulo_E", type: "text" },
  { pg: "emails", sp: "EmailConcat_E", type: "text" },
  { pg: "edificio", sp: "Torre_E", type: "text" },
  { pg: "a_tecnolav", sp: "ATecnolav_E", type: "text" },
  { pg: "activo", sp: "Status_E", type: "bool_activo_inactivo" },
  { pg: "created_at", sp: "Created", type: "iso" }
];

// scripts/migrate/src/resolve.ts
var ResolutionContext = class {
  // ---- text-key maps, built once each source table has been loaded --------
  otByUnivoco = /* @__PURE__ */ new Map();
  // ordenes_trabajo.id_univoco -> id
  bitacoraByUnivoco = /* @__PURE__ */ new Map();
  // bitacoras.id_univoco_bitacora -> id
  compraByBusinessKey = /* @__PURE__ */ new Map();
  // compras.id_compra -> id
  userByConcatName = /* @__PURE__ */ new Map();
  // usuarios.concat_name -> id
  userByUsuarioApp = /* @__PURE__ */ new Map();
  // usuarios.usuario_app -> id
  edificioByNombre = /* @__PURE__ */ new Map();
  // edificios.nombre -> id
  articuloByCodigo = /* @__PURE__ */ new Map();
  // articulos.codigo -> id
  // ---- id sets, used to validate "the SP value already IS the target id" --
  edificioIds = /* @__PURE__ */ new Set();
  articuloIds = /* @__PURE__ */ new Set();
  unidadIds = /* @__PURE__ */ new Set();
  usuarioIds = /* @__PURE__ */ new Set();
  compraIds = /* @__PURE__ */ new Set();
  otIds = /* @__PURE__ */ new Set();
  unresolved = [];
  report(list, sp_id, column, raw_value) {
    this.unresolved.push({
      list,
      sp_id,
      column,
      raw_value: raw_value == null ? "" : String(raw_value)
    });
  }
  /** SP value IS a target-table SP id — validate it actually exists, else null. */
  resolveDirectId(idSet, raw) {
    if (raw == null || raw === "") return null;
    const n = Number(raw);
    if (!Number.isFinite(n)) return null;
    return idSet.has(n) ? n : null;
  }
  resolveByMap(map, raw) {
    if (raw == null) return null;
    const key = String(raw).trim();
    if (!key) return null;
    return map.get(key) ?? null;
  }
  /**
   * Dirty IDArticulo_MS: desktop writes the article CODE, mobile writes the
   * numeric id. Try Number(v) as an articulos id first, else fall back to a
   * codigo match.
   */
  resolveArticuloDirty(raw) {
    if (raw == null || raw === "") return null;
    const n = Number(raw);
    if (Number.isFinite(n) && this.articuloIds.has(n)) return n;
    return this.articuloByCodigo.get(String(raw).trim()) ?? null;
  }
  /** ';'-joined edificios SP ids ('16;17') — take the first that actually resolves. */
  resolveEdificioFirst(raw) {
    if (raw == null || raw === "") return null;
    for (const token of String(raw).split(";")) {
      const n = Number(token.trim());
      if (Number.isFinite(n) && this.edificioIds.has(n)) return n;
    }
    return null;
  }
  /** Same multi-value column, but returns every valid id (for the stock_edificios junction). */
  splitEdificioIds(raw) {
    if (raw == null || raw === "") return [];
    return String(raw).split(";").map((s) => Number(s.trim())).filter((n) => Number.isFinite(n) && this.edificioIds.has(n));
  }
  /** aprobaciones.compra_id: try the SP id first, else a business-key column. */
  resolveCompra(rawId, rawBusinessKey) {
    if (rawId != null && rawId !== "") {
      const n = Number(rawId);
      if (Number.isFinite(n) && this.compraIds.has(n)) return n;
    }
    if (rawBusinessKey != null && rawBusinessKey !== "") {
      return this.compraByBusinessKey.get(String(rawBusinessKey).trim()) ?? null;
    }
    return null;
  }
  toUnresolvedCsv() {
    const escape = (v) => `"${v.replace(/"/g, '""')}"`;
    const rows = this.unresolved.map(
      (u) => `${escape(String(u.list))},${escape(String(u.sp_id))},${escape(u.column)},${escape(u.raw_value)}`
    );
    return ["list,sp_id,column,raw_value", ...rows].join("\n") + "\n";
  }
};

// scripts/sync/catalog-sync.ts
function requireEnv(names) {
  const missing = names.filter((name) => !process.env[name]?.trim());
  if (missing.length > 0) {
    throw new Error(`Missing required environment variable(s): ${missing.join(", ")}`);
  }
  return Object.fromEntries(names.map((name) => [name, process.env[name].trim()]));
}
function toId(spId) {
  const n = Number(spId);
  if (!Number.isFinite(n)) throw new Error(`SharePoint item id is not numeric: ${spId}`);
  return n;
}
async function upsertBatched(supabase, table, rows, batchSize = 500) {
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const { error } = await supabase.from(table).upsert(batch, { onConflict: "id" });
    if (error) throw new Error(`Upsert failed on "${table}" (batch starting at row ${i}): ${error.message}`);
  }
}
async function deactivateMissing(supabase, table, activeColumn, currentIds) {
  if (currentIds.size === 0) {
    console.warn(`  ${table}: 0 items fetched from SharePoint \u2014 skipping deactivation (looks like a fetch issue, not real drift)`);
    return 0;
  }
  const { data, error } = await supabase.from(table).select("id").eq(activeColumn, true);
  if (error) throw new Error(`Fetch active ids failed on "${table}": ${error.message}`);
  const toDeactivate = (data ?? []).map((r) => r.id).filter((id) => !currentIds.has(id));
  if (toDeactivate.length === 0) return 0;
  const { error: updError } = await supabase.from(table).update({ [activeColumn]: false }).in("id", toDeactivate);
  if (updError) throw new Error(`Deactivate failed on "${table}": ${updError.message}`);
  return toDeactivate.length;
}
async function syncList(graph, supabase, siteId, ctx, spec) {
  const displayName = SP_LISTS[spec.listKey];
  const listId = await graph.resolveListId(siteId, displayName);
  let items = await graph.fetchAllItems(siteId, listId);
  if (spec.filterItem) {
    const before = items.length;
    items = items.filter(spec.filterItem);
    if (before - items.length > 0) {
      console.warn(`  ${spec.table}: skipped ${before - items.length} row(s) from another app (shared "99." list)`);
    }
  }
  const rows = items.map((item) => {
    const row = { id: toId(item.id), ...mapRow(spec.mapping, item.fields) };
    if (spec.resolveExtra) Object.assign(row, spec.resolveExtra(ctx, item.fields));
    for (const col of spec.excludeColumns ?? []) delete row[col];
    return row;
  });
  await upsertBatched(supabase, spec.table, rows);
  let deactivated = 0;
  if (spec.activeColumn) {
    const currentIds = new Set(rows.map((r) => r.id));
    deactivated = await deactivateMissing(supabase, spec.table, spec.activeColumn, currentIds);
  }
  return { result: { table: spec.table, fetched: items.length, upserted: rows.length, deactivated }, rows };
}
async function syncAll(graph, supabase, siteUrl) {
  const siteId = await graph.resolveSiteId(siteUrl);
  const ctx = new ResolutionContext();
  const results = [];
  const edificios2 = await syncList(graph, supabase, siteId, ctx, {
    listKey: "edificios",
    table: "edificios",
    mapping: edificios,
    activeColumn: "activo"
  });
  results.push(edificios2.result);
  for (const row of edificios2.rows) {
    const nombre = row.nombre;
    if (nombre) ctx.edificioByNombre.set(nombre, row.id);
  }
  results.push(
    (await syncList(graph, supabase, siteId, ctx, { listKey: "articulos", table: "articulos", mapping: articulos, activeColumn: "activo" })).result
  );
  results.push(
    (await syncList(graph, supabase, siteId, ctx, {
      listKey: "frecuencias",
      table: "frecuencias",
      mapping: frecuencias,
      activeColumn: "activo"
    })).result
  );
  results.push(
    (await syncList(graph, supabase, siteId, ctx, {
      listKey: "unidades",
      table: "unidades",
      mapping: unidades,
      activeColumn: "activa",
      resolveExtra: (rctx, fields) => ({
        edificio_id: rctx.resolveByMap(rctx.edificioByNombre, fields[unidadesResolutions[0].sp])
      })
    })).result
  );
  results.push(
    (await syncList(graph, supabase, siteId, ctx, {
      listKey: "emailsNotificacion",
      table: "emails_notificacion",
      mapping: emailsNotificacion,
      activeColumn: "activo"
    })).result
  );
  results.push(
    (await syncList(graph, supabase, siteId, ctx, {
      listKey: "perfilesPermisos",
      table: "perfiles_permisos",
      mapping: perfilesPermisos,
      activeColumn: "activo",
      excludeColumns: ["imagen_path", "imagen_no_selected_path"],
      // Same filter the migration applies: shared "99." list, keep only this app's rows.
      filterItem: (item) => {
        const app = mapRow(perfilesPermisos, item.fields).aplicacion;
        return app === "Desktop" || app === "Mantenimiento";
      }
    })).result
  );
  results.push(
    (await syncList(graph, supabase, siteId, ctx, {
      listKey: "iconosApp",
      table: "iconos_app",
      mapping: iconosApp,
      activeColumn: null,
      // no soft-delete flag on this table
      excludeColumns: ["icono_path"]
    })).result
  );
  return results;
}
async function main() {
  const env = requireEnv([
    "MS_TENANT_ID",
    "MS_CLIENT_ID",
    "MS_CLIENT_SECRET",
    "SP_SITE_URL",
    "SUPABASE_URL",
    "SUPABASE_SERVICE_ROLE_KEY"
  ]);
  const graph = createGraphClient({ tenantId: env.MS_TENANT_ID, clientId: env.MS_CLIENT_ID, clientSecret: env.MS_CLIENT_SECRET });
  const supabase = createClient(env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
  console.log(`Starting catalog sync against ${env.SP_SITE_URL}...
`);
  const results = await syncAll(graph, supabase, env.SP_SITE_URL);
  console.log("\n=== Catalog sync summary ===");
  console.table(results);
  const deactivatedTotal = results.reduce((sum, r) => sum + r.deactivated, 0);
  if (deactivatedTotal > 0) {
    console.warn(`
${deactivatedTotal} row(s) deactivated this run \u2014 verify this is real drift, not a mapping/id mismatch.`);
  }
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    console.error("\nCatalog sync failed:", err instanceof Error ? err.message : err);
    process.exitCode = 1;
  });
}

// scripts/sync/vercel-handler.ts
async function handler(req, res) {
  const secret = process.env.CRON_SECRET;
  if (!secret || req.headers.authorization !== `Bearer ${secret}`) {
    res.status(401).json({ error: "Unauthorized" });
    return;
  }
  try {
    const env = requireEnv(["MS_TENANT_ID", "MS_CLIENT_ID", "MS_CLIENT_SECRET", "SP_SITE_URL", "SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"]);
    const graph = createGraphClient({ tenantId: env.MS_TENANT_ID, clientId: env.MS_CLIENT_ID, clientSecret: env.MS_CLIENT_SECRET });
    const supabase = createClient2(env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
    const results = await syncAll(graph, supabase, env.SP_SITE_URL);
    const deactivated = results.reduce((sum, r) => sum + r.deactivated, 0);
    res.status(200).json({ ok: true, deactivated, results });
  } catch (err) {
    console.error("Catalog sync failed:", err instanceof Error ? err.message : err);
    res.status(500).json({ ok: false, error: err instanceof Error ? err.message : String(err) });
  }
}
export {
  handler as default
};
